config/routes.rb
Rails.application.routes.draw do

root 'songs#index'
resources :sessions, only: [ :new, :create, :destroy ]
resources :users, only: [ :new, :create, :update, :edit, :show ] do
  member do
    get :activate
  end
end
resources :songs do
  resources :comments, only: [ :create, :destroy ]
end
resource :likeship, only: [ :create, :destroy ]
resources :notifications, only: [ :index, :destroy ] do
  collection do
    post :count
    delete :clear
  end
end
resources :password_resets, only: [ :new, :create, :edit, :update]
get 'login', to: 'sessions#new', as: :login
get 'signup', to: 'users#new', as: :signup
delete 'logout', to: 'sessions#destroy', as: :logout
get 'collect', to: 'songs#collect', as: :collect
get 'user_songs', to: 'users#user_songs', as: :user_songs
get 'favorite_songs', to: 'users#favorite_songs', as: :favorite
get 'recent_comments', to: 'users#recent_comments', as: :recent_comments
get 'language', to: 'users#language', as: :set_locale

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject, polymorphic: true

  scope :named, -> (name) { where(name: name) }
  scope :unread, -> { where(read: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :require_login

  def index
    @notifications = current_user.notifications
                                                   .order(id: :desc)
                                                   .page(params[:page])
                                                   .per(25)

   @notifications.unread.update_all(read: true, updated_at: Time.now.utc)
   @user_panel = true
  end

  def destroy
    @notification = current_user.notifications.find params[:id]
    @notification.destroy
  end

  def clear
    @notifications = current_user.notifications
    current_user.notifications.delete_all
    respond_to do |format|
      format.html { redirect_to notifications_path }
      format.js 
    end
  end

  def count
    render text: current_user.notifications.unread.count
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notifications.html.slim
- cache @notifications do 
  #notifications
    .ui.animated.list
      - @notifications.each do |notification|
        .ui.feed
          .event id="notification-#{notification.id}"
            = render "notifications/notification/#{notification.name}", notification: notification
            = link_to notification_path(notification), remote: true, method: :delete, data: { confirm: "#{t('form.are_you_sure')}" }, class: "pull-right delete-notification" do
                 i.red.trash.icon

app/views/notifications/clear.js.erb
$('#notifications').html("<%= j render 'notifications' %>")

app/views/notifications/destroy.js.erb
$(function(){
    $('#notification-<%= @notification.id %>').addClass('animated lightSpeedOut')
                               .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', 
        function(){
        $(this).remove();
        }
    );
});

app/views/notifications/index.html.slim
    .ui.stacked.segment
      .ui.ribbon.green.label 
        h3.notifications-header =t('.notifications')
      = link_to "#{t('.empty_notifications')}", clear_notifications_path, remote: true, method: :delete, data: { confirm: "#{t('form.are_you_sure')}", disable_with: "#{t('.clearing')}" }, class: "ui red button pull-right"
      = render 'notifications'
      = paginate @notifications