config/routes.rb
Rails.application.routes.draw do

root 'songs#index'
resources :sessions, only: [ :new, :create, :destroy ]
resources :users, only: [ :new, :create, :update, :edit, :show ] do
  member do
    get :activate
  end
end
resources :songs do
  resources :comments, only: [ :create, :destroy ]
end
resource :likeship, only: [ :create, :destroy ]
resources :notifications, only: [ :index, :destroy ] do
  collection do
    post :count
    delete :clear
  end
end
resources :password_resets, only: [ :new, :create, :edit, :update]
get 'login', to: 'sessions#new', as: :login
get 'signup', to: 'users#new', as: :signup
delete 'logout', to: 'sessions#destroy', as: :logout
get 'collect', to: 'songs#collect', as: :collect
get 'user_songs', to: 'users#user_songs', as: :user_songs
get 'favorite_songs', to: 'users#favorite_songs', as: :favorite
get 'recent_comments', to: 'users#recent_comments', as: :recent_comments
get 'language', to: 'users#language', as: :set_locale

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  has_many :songs, dependent: :delete_all
  has_many :comments, dependent: :destroy
  has_many :likeships, foreign_key: "user_id", dependent: :destroy
  has_many :notifications, dependent: :delete_all
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[A-Za-z][A-Za-z0-9._-]{2,19}\z/
  validates :name, presence: true, 
                            length: { maximum: 50 }, 
                            format: { with: VALID_NAME_REGEX },
                            uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: true }
  validates :password, presence: true, 
                                  confirmation: true,
                                  length: { in: 6..16 },
                                  on: :create
  validates :bio, length: { maximum: 140 }

  #Find user by name
  def to_param
    name
  end
  
  #Like
  def liking?(likeable)
    likeships.find_by(likeable)
  end

  def like!(type, id)
    likeships.create!(likeable_type: type, likeable_id: id)
  end  

  def unlike!(type, id)
    likeships.find_by(likeable_type: type, likeable_id: id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_login, only: [ :edit, :update ]
before_action :find_correct_user, only: [ :edit, :update ]
before_action :not_login_user, only: [ :new, :create ]
before_action :find_user, only: [ :show, :user_songs, :favorite_songs, :recent_comments ]

  def show
    if @user
      @songs = @user.songs.order("created_at desc")
    else
      redirect_to root_path
      flash[:error] = "#{t('.no_user')}"
    end
  end

  def new
    @user = User.new
    @signup = true
    render layout: "users_form"
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  	  flash[:success] = "#{t('.successfully')}"
        respond_to do |format|
          format.html { redirect_to root_path }
          format.js
        end
  	else
        respond_to do |format|
          format.html { render 'new' }
          format.js
        end
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(update_user_params)
      flash[:success] = "#{t('.successfully')}"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash.now[:error] = "#{t('.faild')}"
      respond_to do |format|
        format.html { render 'edit' }
        format.js
      end
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      flash[:success] = "#{t('.activated')}"
      auto_login(@user)
    else
      not_authenticated
    end
  end

  def user_songs
    @songs = @user.songs.order("created_at desc")
  end

  def favorite_songs
    songs_id = @user.likeships.where("likeable_type = ?", "Song").collect(&:likeable_id)
    @songs = Song.find(songs_id).reverse!

    respond_to do |format|
      format.js
    end
  end

  def recent_comments
    @comments = @user.comments.includes(:song).order("created_at desc")
    respond_to do |format|
      format.js
    end
  end

  def language
    if params[:locale]
      I18n.default_locale = params[:locale]
      redirect_to :back
    end
  end

  private

  def find_correct_user
    @user = User.find_by_name(params[:id])
    unless current_user?(@user)
      flash[:warning] = "#{t('permission_denied')}"
      redirect_to root_path
    end
  end

  def find_user
    @user = User.find_by_name(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)   
  end

  def update_user_params
    params.require(:user).permit(:bio, :avatar, :locale, :password, :password_confirmation)
  end

  def not_login_user
    if logged_in?
      redirect_to root_path
      flash[:warning] = "#{t('users.has_already_logged_in')}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  def require_login
    if !logged_in?
      redirect_to login_url
      flash[:warning] ="#{I18n.t('users.login_first')}"
    end
  end
end

app/views/users/_user_panel.html.slim
.ui.large.vertical.labeld.menu
  .ui.header.item.center.teal.label 
    = link_to current_user
      = image_tag current_user.avatar_url(:large), class: "ui circular image thumb user-avatar run-popup", data: { content: "#{t('.check_profile')}", variation: "large"}
  = link_to notifications_path, class: "item"
    - count = current_user.notifications.unread.count
    - if count > 0
      #unread-count.ui.red.label = count
    - else
      #unread-count.ui.label = count
    | #{t('notifications.index.notifications')}
  = link_to songs_path, class: "item"
    i.home.green.icon
    | #{t('layouts.users_form.home')}
  = link_to :collect, class: "item"
    i.star.yellow.icon
    | #{t('.likes')}
  = link_to edit_user_path(current_user), class: "item"
    i.settings.blue.icon
    | #{t('.settings')}
  = link_to :logout, method: :delete, class: "item"
    i.sign.out.red.icon
    | #{t('users.logout')}

app/views/users/create.js.erb
$('.ui.form').removeClass('loading')
<% if @user.errors.empty? %>
  Turbolinks.visit('<%= root_path %>');
<% else %>
  $('#signup-errors').html("<%= j render 'shared/error_messages', object: @user %>");
  $('#error_explanation').transition('tada');
<% end %>

app/views/users/edit.html.slim
.ui.grid
  .six.wide.column
  .four.wide.column
    .ui.form
      #user-edit-errors
        = render 'shared/error_messages', object: @user
      = form_for @user, remote: true do |f|
        .ui.center.aligned.field.basic.segment
          = image_tag(current_user.avatar_url(:large), class: "ui image circular thumb user-avatar user-avatar-upload run-popup", data: { content: "#{t('.upload_avatar')}", position: "top center" })
          = f.file_field :avatar, class: "upload-avatar"
        .inline.fields.ui.center.aligned.basic.segment
          - I18n.available_locales.each do |locale|
            .field
              .ui.radio.checkbox.checked
                = f.radio_button(:locale, "#{locale}")
                = f.label t("locales.#{locale}")
        .field
          = f.text_field :email, placeholder: "#{t('activerecord.attributes.user.email')}", disabled: "disabled"
        .field
          = f.text_field :bio, placeholder: "#{t('activerecord.attributes.user.bio')}"
        .ui.buttons.session-buttons
          = link_to "#{t('.my_page')}", user_path(@user), class: "ui button orange"
          .or
          = f.submit "#{t('form.save')}", class: "ui blue button"

app/views/users/favorite_songs.js.erb
$('.status-panel').html("<%= j render 'songs/play_list', songs: @songs %>")

app/views/users/new.html.slim
.signup-form
  #signup-errors
    = render 'shared/error_messages', object: @user
  = form_for @user, remote: true do |f|
    .ui.form
      .field
        .ui.left.icon.large.input
           = f.text_field :name, placeholder: "#{t('activerecord.attributes.user.name')}"
           i.user.icon
      .field
        .ui.left.icon.large.input
           = f.text_field :email, placeholder: "#{t('activerecord.attributes.user.email')}"
           i.mail.icon
      .field
        .ui.left.icon.large.input
           = f.password_field :password, placeholder: "#{t('activerecord.attributes.user.password')}"
           i.lock.icon
      .field
        .ui.left.icon.large.input
           = f.password_field :password_confirmation, placeholder: "#{t('activerecord.attributes.user.password_confirmation')}"
           i.lock.icon
      = f.submit "#{t('users.signup')}", class: "ui fluid green large button", data: { disable_with: "#{t('form.submitting')}" }

app/views/users/recent_comments.js.erb
$('.status-panel').html("<%= j render 'comments/recent_comments', comments: @comments %>")

app/views/users/show.html.slim
#canvas-bg
canvas#particles
.ui.grid
  .three.wide.column
  .ten.wide.column
    #user-show.ui.grid
      .one.wide.column
      .fourteen.wide.column
        .ui.grid
          .one.wide.column
          .ui.five.wide.column.center.aligned.info-column
            = image_tag(@user.avatar_url(:large), class: "ui image circular lg  run-popup")
            .center
              h3 = @user.name
            .center.bio
              = @user.bio
            .ui.divider
            - class_name = "ui left aligned basic segment" unless I18n.locale.to_s == "zh-CN"
            .user-status class="#{class_name}"
              .user-created-at
                p #{t('.created_at')}: #{time_ago_in_words(@user.created_at)} #{t('.ago')}
              .user-songs-count
                p #{t('.total_songs')}: #{t('.songs_count', count: @user.songs.count)}
              .user-comments-count
                p #{t('.total_comments')}: #{t('.comments_count', count: @user.comments.count)}
          .nine.wide.column.content-column
              .ui.secondary.large.menu data-loading="#{t('.loading')}"
                = link_to "#{t('.songs')}", user_songs_url+"?id=#{@user.name}", remote: true, class: "active item"
                = link_to "#{t('users.user_panel.likes')}", favorite_url+"?id=#{@user.name}", remote: true, class: "item"
                = link_to "#{t('comments.comments')}", recent_comments_url+"?id=#{@user.name}", remote: true, class: "item"
              .status-panel
                = render 'songs/play_list', songs: @songs

audio id="player" data-xiami_id="-1"

javascript:
  $(function() {
    if($("#particles").size()>0){
      (function() {
        var width, height, largeHeader, canvas, ctx, circles, target, animateHeader = true;
        width = $('#canvas-bg').width();
        height= $('#canvas-bg').height();
        target = {x: 0, y: height};
        largeHeader = document.getElementById('canvas-bg');
        largeHeader.style.height = height+'px';
        canvas = document.getElementById('particles');
        canvas.width = width;
        canvas.height = height;
        ctx = canvas.getContext('2d');

        circles = [];
        for(var x = 0; x < width*0.5; x++) {
          var c = new Circle();
          circles.push(c);
        }
        animate();
          window.addEventListener('resize',function(){
          width = window.innerWidth;
              canvas.width = width;
          });
          function animate() {
              if(animateHeader) {
                  ctx.clearRect(0,0,width,height);
                  for(var i in circles) {
                      circles[i].draw();
                  }
              }
              requestAnimationFrame(animate);
          }
          function Circle() {
              var _this = this;

              (function() {
                  _this.pos = {};
                  init();
              })();

              function init() {
                  _this.pos.x = Math.random()*width;
                  _this.pos.y = height+Math.random()*100;
                  _this.alpha = 0.1+Math.random()*0.3;
                  _this.scale = 0.1+Math.random()*0.3;
                  _this.velocity = Math.random();
              }

              this.draw = function() {
                  if(_this.alpha <= 0) {
                      init();
                  }
       
                  _this.pos.x -=0.1;
                  _this.pos.y -= _this.velocity;
                  _this.alpha -= 0.0005;
                  ctx.beginPath();
                  ctx.arc(_this.pos.x, _this.pos.y, _this.scale*10, 0, 2 * Math.PI, false);
                  ctx.fillStyle = 'rgba(255,255,255,'+ _this.alpha+')';
                  ctx.fill();
              };
          }
      })();
    }})

app/views/users/update.js.erb
<% if @user.errors.empty? %>
  Turbolinks.visit('<%= user_path(@user) %>');
<% else %>
  $('#user-edit-errors').html("<%= j render 'shared/error_messages', object: @user %>")
  $('#error_explanation').transition('tada');
<% end %>

app/views/users/user_songs.js.erb
$('.status-panel').html("<%= j render 'songs/play_list', songs: @songs %>")