config/routes.rb
Rails.application.routes.draw do

root 'songs#index'
resources :sessions, only: [ :new, :create, :destroy ]
resources :users, only: [ :new, :create, :update, :edit, :show ] do
  member do
    get :activate
  end
end
resources :songs do
  resources :comments, only: [ :create, :destroy ]
end
resource :likeship, only: [ :create, :destroy ]
resources :notifications, only: [ :index, :destroy ] do
  collection do
    post :count
    delete :clear
  end
end
resources :password_resets, only: [ :new, :create, :edit, :update]
get 'login', to: 'sessions#new', as: :login
get 'signup', to: 'users#new', as: :signup
delete 'logout', to: 'sessions#destroy', as: :logout
get 'collect', to: 'songs#collect', as: :collect
get 'user_songs', to: 'users#user_songs', as: :user_songs
get 'favorite_songs', to: 'users#favorite_songs', as: :favorite
get 'recent_comments', to: 'users#recent_comments', as: :recent_comments
get 'language', to: 'users#language', as: :set_locale

end

app/models/song.rb
class Song < ActiveRecord::Base
  include SongsHelper
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :likeships, as: :likeable, foreign_key: "likeable_id", dependent: :destroy
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 10000 }
  validates :title, :artist, presence: { message: :fetch }
  validates :s_id, presence: true, uniqueness: true, numericality: { greater_than: 0 }

  before_validation :set_xiami_info

  scope :hot_songs, -> { joins(:likeships).
                                       group('songs.id').
                                       order('count(likeships.id) desc').
                                       limit(10) }

  def set_xiami_info
      get_xiami_info(self)
  end

end

app/controllers/songs_controller.rb
  class SongsController < ApplicationController
  before_action :require_login, only: [ :new, :create, :collect, :edit, :update, :destroy ]
  before_action :find_song, only: [ :edit, :update, :destroy ]

  def index
    @songs = Song.includes(:user).all.order("created_at desc").page params[:page]
    @hot_songs = Song.hot_songs
    @user_panel = true
  end

  def new
    @song = current_user.songs.build
  end

  def show
    @song = Song.includes(:comments).find(params[:id])
    @comments = @song.comments.includes(:user, :likeships).page(params[:page]).per(25)
  end

  def collect
    songs_id = current_user.likeships.where("likeable_type = ?", "Song").collect(&:likeable_id)
    songs = Song.find(songs_id).reverse!
    @user_panel = true
    if songs.empty?
      @recommend = true
      @songs = Song.hot_songs.page params[:page]
    else
      @songs = Kaminari.paginate_array(songs).page(params[:page])
    end
  end
  
  def create
   @song = current_user.songs.build(song_params)
    if @song.save
      flash.now[:success] = "#{t('.success')}"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash.now[:error] = "#{t('.faild')}"
      respond_to do |format|
        format.html { render 'new' }
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @song.update_attributes params.require(:song).permit(:content)
      flash.now[:success] = "#{t('.successfully')}"
      respond_to do |format|
        format.html { redirect_to @song }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'edit' }
        format.js
      end
    end
  end

  def destroy
    @song = current_user.songs.find(params[:id])
    if @song.destroy
      flash[:success] = "#{t('.successfully')}"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def song_params
    params.require(:song).permit(:s_id, :content)
  end

  def find_song
    @song = current_user.songs.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:warning] = "#{t('permission_denied')}"
    redirect_to root_path
  end

end

app/helpers/songs_helper.rb
module SongsHelper
  require 'open-uri'
  require 'json'

  def get_xiami_info(object = {})
      begin
        url = "http://xiamirun.avosapps.com/run?song=http://www.xiami.com/song/" + object.s_id.to_s
        doc = JSON.parse(open(url).read)
      rescue JSON::ParserError
        object.title = ""
      else
        object.title = doc['title']
        object.artist = doc['artist']
        object.pic = doc['cover']
      end
  end
end

app/views/songs/_form.html.slim
= form_for song, remote: true do |f|
  #song-errors
    = render 'shared/error_messages', object: song
  .ui.form
    .fields
      .eight.wide.field
        .ui.labeled.input
          .ui.teal.label http://www.xiami.com/song/
          - if action_name == "edit"
            = f.text_field :s_id, placeholder: "#{t('activerecord.attributes.song.s_id')}", disabled: "disabled"
          - else
            = f.text_field :s_id, placeholder: "#{t('activerecord.attributes.song.s_id')}"
      .four.wide.field
        = f.text_field :title, placeholder: "#{t('.title')}", disabled: "disabled"
      .four.wide.field
        = f.text_field :artist, placeholder: "#{t('.singer')}", disabled: "disabled"
    .field
      = f.text_area :content, placeholder: "#{t('.content')}"
      = f.hidden_field :pic
    = f.submit "#{t('form.submit')}", class: "ui submit button orange right floated", data: { disable_with: "#{t('form.submitting')}" }
    span.pull-right.help-inline Ctrl+Enter
javascript:
  if($('input#song_title').val().length > 0){
    title = $('input#song_title').val().replace(/&#039;/,"'")
    $('input#song_title').val(title)  
    }
#xiami-errors data-blank="#{t('activerecord.attributes.song.s_id')} #{t('.cant_be_blank')}" data-cant_fetch="#{t('songs.cant_fetch')}" data-passed="#{t('.passed')}"

app/views/songs/_play_list.html.slim
- if songs.any?
  - for song in songs
    .songs-list
      a data-xiami_id="#{song.s_id}" class="ui playBtn"
        i.play.icon
      = link_to song.title.html_safe, song
      .ui.hidden.divider
- else
  .ui.center.aligned.basic.segment
    p =t('.no_songs_yet')
    p ...>_<...

app/views/songs/_share_buttons.html.slim
p.share-button
  a href="http://service.weibo.com/share/share.php?url=#{song_url(@song)}&type=3&pic=#{song.pic}&title=#{song.title}" target="_blank"
    i.weibo.red.icon
  a href="https://twitter.com/intent/tweet?url=#{song_url(song)}&text=#{song.title}&via=Ting"  target="_blank"
    i.twitter.blue.icon
  a href="http://www.facebook.com/sharer.php?u=#{song_url(song)}"  target="_blank"
    i.facebook.purple.icon

app/views/songs/_song.html.slim
- cache [song, index] do
  section.ui.two.column.grid.segment.stacked.songs-list id="song-#{song.id}"
    .five.wide.column
      - unless index
        .ui.left.red.corner.label
          i.heart.icon
      .album-pic
        .outer-pic.ui.circular.image
          img src="#{song.pic}"
        a data-xiami_id="#{song.s_id}" class="ui corner label playBtn"
          i.play.icon
    .eleven.wide.column.song-info
      - if current_user == song.user
        .operate
          = link_to edit_song_path(song), class: "edit-song" do 
            i.green.pencil.icon
          = link_to song_path(song), data: { method: "delete", confirm: "#{t('form.are_you_sure')}", remote: true } do 
            i.red.trash.icon
      .ui.right
        h3.header
          i.orange.sound.icon
          = link_to song.title.html_safe, song
        .singer
          | #{t('activerecord.attributes.song.artist')}: 
          a = song.artist
        .song-content 
          = parse_text(song.content)
      .song-footer
        .com-count
          - author = song_url(song) + "#comments"
          = link_to author do 
            i.green.comment.icon
            = song.comments.size
        .musician
          = image_tag(song.user.avatar_url(:thumb), class: "ui avatar image")
          = link_to song.user.name, song.user

app/views/songs/_songs.html.slim
- cache [:songs, @songs] do
  - if index
    - if logged_in?
      - class_name = "modal-en" unless I18n.locale.to_s == "zh-CN"
      .ui.green.button.modal-toggle class="#{class_name}" =t('.share_a_song')
      .ui.modal.song-form
        i.close.red.icon
        .content
          = render 'songs/form', song: current_user.songs.new

  - if @recommend
    .ui.orange.message
      .ui.center.aligned.basic.segment =t('.recommend_songs')
  #songs data-image="#{asset_path("loading.gif")}"
    - for song in @songs
      = render 'song', song: song, index: index
    #pagination data-loaded="#{t('.loaded')}"
      = paginate @songs
          
  audio id="player" data-xiami_id="-1"

app/views/songs/collect.html.slim
= render 'songs', index: false

app/views/songs/create.js.erb
<% if @song.errors.empty? %>
    new_song = "<%= j render 'song', song: @song, index: true %>";
    $('#songs').prepend(new_song);
    animated();
<% else %>
  $('#song-errors').html("<%= j render 'shared/error_messages', object: @song %>");
  $('#error_explanation').transition('tada');
<% end %>
$('.ui.form').removeClass('loading')
$('.ui.form .button').removeClass('disabled')

function animated() {
  $('#error_explanation').html("");
  $('#song-<%= @song.id %>').addClass('animated flipInX');
  $('#new_song').trigger('reset');
  $('.close.red').click();
}

app/views/songs/destroy.js.erb
$(function(){
    $('#song-<%= @song.id %>').addClass('animated flipOutX')
                                                  .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', 
        function(){
            $('#song-<%= @song.id %>').remove();
        }
    );
});

app/views/songs/edit.html.slim
 .ui.grid
   .four.wide.column
   #song-edit.eight.wide.column
     = render 'form', song: @song

app/views/songs/index.html.slim
= render 'songs', index: true

app/views/songs/new.html.slim
 .ui.grid
   .five.wide.column
   .six.wide.column
     = render 'form', song: @song

app/views/songs/show.html.slim
- id = @song.s_id
- user = @song.user
- cache @song do
  .ui.grid
    .four.wide.column
    .eight.wide.column
      .ui.one.column.grid.songs-list id="song-#{@song.id}"
        .sixteen.wide.column.song-info

          .song-container.ui.grid
            .ui.five.wide.column
              .album-pic
                .outer-pic.ui.circular.image.dimmer-image
                  .ui.dimmer
                    .content
                      .center
                        a.playBtn data-xiami_id="#{@song.s_id}"
                          i.ui.red.huge.play.icon
                  img src="#{@song.pic}"

            .ui.eleven.wide.column
              .song-panel
                h3.header
                  i.orange.sound.icon
                  = link_to @song.title.html_safe, @song
                p
                  i.user.green.icon
                  a = @song.artist
                p.song-toolbar
                  = link_to user
                    = image_tag(@song.user.avatar_url(:small), class: "ui mini-avatar avatar image run-popup", data: { content: "#{user.name}", position: "bottom center" } )
                  span.song-tools-divider •
        
                  i.teal.calendar.icon
                  = @song.created_at.strftime("%F")
                  span.song-tools-divider •

                  span.item id="like-song-#{@song.id}"
                    - @likeable = Likeship.likeable(@song)
                    = likeable_likes_tag @likeable                  

                  - if current_user == user
                    span.song-tools-divider •
                    = link_to edit_song_path(@song) do
                      i.green.icon.pencil
                    span.song-tools-divider •

                    = link_to song_path(@song), method: :delete, data: { confirm: "#{t('form.are_you_sure')}" }
                      i.red.icon.trash                  
                = render 'share_buttons', song: @song

            .ui.sixteen.wide.column
              .song-content 
                = parse_text(@song.content)
          .song-footer

      .ui.horizontal.icon.divider
        i.circular.red.chat.icon

      #comments
        .column
          .ui.comments
            - if @comments.any?
              = render @comments
            - else
              .ui.center.aligned.basic.segment =t('comments.no_comments_yet')

          = paginate @comments

          .ui.horizontal.icon.divider
            i.circular.green.pencil.icon
          - if logged_in?
            = render 'comments/form'
          - else
            .ui.center.aligned.basic.segment
              = link_to :login
                .ui.animated.fade.blue.button
                  .visible.content =t('users.login_first')
                  .hidden.content =t('users.login')
  audio id="player" data-xiami_id="-1"

app/views/songs/update.js.erb
<% if @song.errors.empty? %>
  Turbolinks.visit('<%= song_path(@song) %>')
<% else %>
  $('#song-errors').html("<%= j render 'shared/error_messages', object: @song %>");
  $('#error_explanation').transition('tada');
<% end %>