config/routes.rb
Rails.application.routes.draw do

root 'songs#index'
resources :sessions, only: [ :new, :create, :destroy ]
resources :users, only: [ :new, :create, :update, :edit, :show ] do
  member do
    get :activate
  end
end
resources :songs do
  resources :comments, only: [ :create, :destroy ]
end
resource :likeship, only: [ :create, :destroy ]
resources :notifications, only: [ :index, :destroy ] do
  collection do
    post :count
    delete :clear
  end
end
resources :password_resets, only: [ :new, :create, :edit, :update]
get 'login', to: 'sessions#new', as: :login
get 'signup', to: 'users#new', as: :signup
delete 'logout', to: 'sessions#destroy', as: :logout
get 'collect', to: 'songs#collect', as: :collect
get 'user_songs', to: 'users#user_songs', as: :user_songs
get 'favorite_songs', to: 'users#favorite_songs', as: :favorite
get 'recent_comments', to: 'users#recent_comments', as: :recent_comments
get 'language', to: 'users#language', as: :set_locale

end

app/views/layouts/_navbar.html.slim
- if logged_in?
  = render 'users/user_panel'
- else
  .ui.grid.form.basic.segment
    #full-button.ui.buttons.sixteen.wide.column
      = link_to "#{t('users.signup')}", :signup, class: "ui blue inverted button"
      .or
      = link_to "#{t('users.login')}", :login, class: "ui purple inverted button"
  .ui.red.inverted.center.aligned.segment
    #site-status
      = link_to "中文简体", set_locale_url(locale: "zh-CN"), class: "ui red label"
      = link_to "English", set_locale_url(locale: "en"), class: "ui red label"
      .ui.divider
      .site-params
        p #{t('.total_users')}: #{t('users.show.users_count', count: User.count)}
        p #{t('users.show.total_songs')}: #{t('users.show.songs_count', count: Song.count)}
        p #{t('users.show.total_comments')}: #{t('users.show.comments_count', count: Comment.count)}

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ting
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  body
    .ui.fixed.green.inverted.menu.center.aligned.segment
      = link_to root_path, id: "logo", class: "item"
        i.music.icon
    = render 'shared/flash'
    .container.animated.fadeIn
      - if @user_panel
        .ui.grid
          .two.wide.column
          #main.nine.wide.column
            = yield
            .right.ui.rail
              .ui.sticky
                = render 'layouts/navbar'
      - else
        = yield

app/views/layouts/users_form.html.slim
doctype html
html
  head
    title Ting
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

    .pin-button
      = link_to "#{t('.home')}", songs_path, class: "ui blue inverted pull-right button"
      - if @signup
        = link_to "#{t('users.login')}", :login, class: "ui green inverted pull-right button"
      - else
        = link_to "#{t('users.signup')}", :signup, class: "ui green inverted pull-right button"
    img#rainyday src="#{asset_path("night.jpg")}"
    .wallpaper
      = yield